### ISSUE TITLE
'Cancel' button does not cancel.

### ISSUE THREAD

**Issue by adamburton** [Pligg/pligg-cms#233]
Hello,
I am testing a fairly fresh installation of 2.0.2. I do not think I have edited anything critical.
This is what I am doing:
- click on Submit
- input a URL
- click Continue
  (Story Title and Description are auto-filled)
- click Cancel

I get a red box with "No Category Selected" in it and a Back button.

If I then:
- click Back
- enter a Category (News)
- click Cancel

I get a red box with "The CAPTCHA answer provided is not correct. Please go back and try again." in it. The Back button is outside of the red box this time.

If I then:
- click Back
- complete the CAPTCHA
- click Cancel

It takes me to the 'Confirm Details' page.

I suppose that what this means is that the Cancel button is not working.
I had the same problem on a previous install.

I am assuming that this is a bug rather than a Support issue. Let me know, though, if I ought to post it to the Support area instead.
Thank you, bye,
Adam.

**Comment by redwinefireplace** [comment]
Adam, Thank you for submitting this bug. It is working in Chrome but not n Firefox. To fix the issue, modify the following code:
1- Open /templates/bootstrap/submit_step_2_center.tpl
2- Change LINE 112
from this 
&lt;button class=&quot;btn btn-default&quot; tabindex=&quot;30&quot; ONCLICK=&quot;history.go(-1)&quot;&gt;Cancel&lt;/button&gt;
to this
&lt;button class=&quot;btn btn-default&quot; tabindex=&quot;30&quot; onclick=&quot;history.go(-1); return false;&quot;&gt;Cancel&lt;/button&gt; 

It should work properly!

**Comment by adamburton** [comment]
Hello redwine,
thank you, that worked.
Is there anything that I can do to assist in editing the code or to report the bug so that the software gets fixed?

I just now did a search for the problem here on github/Pligg and found this post by yankidank from 2014 - https://github.com/Pligg/pligg-cms/issues/192 - does this mean that it has already been reported?

Thank you again for your help, again and again.
Adam.

**Comment by redwinefireplace** [comment]
Hello Adam, I've already submitted the fix as a Pull request to the master Pligg. It will be implemented in the new version. 
https://github.com/redwinefireplace/pligg-cms/commit/bcc2b717bd8196c32126380706bf2f5ae4ff9b90

**Comment by adamburton** [comment]
Ah, okay, thank you redwine.
Some day I might try to learn about all of this so that I can make myself a little bit more useful.
Bye,
Adam.

**Comment by adamburton** [comment]
I am going to Close this issue. I assume that is the appropriate thing to do.
Bye.
