### ISSUE TITLE
Pligg is (not) dead

### ISSUE THREAD

**Issue by chuckroastpligg** [Pligg/pligg-cms#242]
Pligg CMS is dead.
The developers have all jumped ship and are working on releasing a fork called Kliqqi. 
See you all at Kliqqi dot com

**Comment by jiyath** [comment]
You are developing from Pligg CMS or New one???

**Comment by jasongill** [comment]
This is inaccurate - Pligg is very much alive, and a new dedicated developer has been hired to work on a major overhaul of Pligg. We welcome Kliqqi's open source fork of the project and look forward to sharing code and ideas with their development team going forward!
