### ISSUE TITLE
Update readme warning users that Pligg is dead

### ISSUE THREAD

**Issue by ghost** [Pligg/pligg-cms#245]
> This is inaccurate - Pligg is very much alive, and a new dedicated developer has been hired to work on a major overhaul of Pligg.

~ #242

Everything holds up on paper, but pligg.com tells a complete different story

![pligg.com march 2016](https://cloud.githubusercontent.com/assets/6382342/13548171/31f8bec6-e2ea-11e5-86e2-c01c6b025473.png)

and there's a SQL injection patch sitting in the PR requests since almost a month.

**Comment by GenericUK** [comment]
![screenshot_2016-03-12-09-43-18](https://cloud.githubusercontent.com/assets/1609873/13722253/f432c904-e836-11e5-99e8-82888519db63.png)
